collections:
    - name: kubernetes.core
      version: 2.3.2
    - name: git+https://github.com/IvailoNikolov/ansible_collection_helm_ingress.git,main
roles:
  - name: ivailo.ansible_role_helm_rancher_backup
    type: git
    src: https://github.com/IvailoNikolov/ansible_role_helm_rancher_backup.git
    version: master